services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    ports:
      - "8080:80"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/var/www/html:cached
    healthcheck:
      test: ["CMD", "curl", "-sSf", "http://localhost/"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      milk_network:
        aliases:
          - milk-backend
    restart: unless-stopped

  frontend:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - .:/app
    command: >
      sh -c "
      npm install &&
      npm run dev
      "
    tty: true
    stdin_open: true
    networks:
      - milk_network

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ql_ban_sua
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
    - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./database:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - milk_network
    restart: unless-stopped

  playwright:
    build:
      context: ./automation_test
      dockerfile: Dockerfile.test
    profiles:
      - test
    environment:
      - PLAYWRIGHT_TEST_BASE_URL=http://milk-backend:80
    volumes:
      - ./automation_test/playwright-report:/app/playwright-report
    depends_on:
      app:
        condition: service_healthy
      db:
        condition: service_healthy
      frontend:
        condition: service_started
    networks:
      - milk_network

volumes:
  db_data:

networks:
  milk_network:
    driver: bridge