FROM php:8.2-apache

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        libpq-dev curl \
    && docker-php-ext-install pdo pdo_pgsql opcache \
    && a2enmod rewrite \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN a2enmod headers
ENV APACHE_DOCUMENT_ROOT=/var/www/html/public

RUN mkdir -p /var/www/html/public/assets/images && \
    chmod -R 777 /var/www/html/public/assets/images

RUN sed -ri -e 's!/var/www/html!${APACHE_DOCUMENT_ROOT}!g' \
    /etc/apache2/sites-available/*.conf && \
    sed -ri -e 's!/var/www/!${APACHE_DOCUMENT_ROOT}!g' \
    /etc/apache2/apache2.conf \
    /etc/apache2/conf-available/*.conf

RUN echo "<Directory /var/www/html/public>" >> /etc/apache2/apache2.conf && \
    echo "AllowOverride All" >> /etc/apache2/apache2.conf && \
    echo "</Directory>" >> /etc/apache2/apache2.conf

RUN echo "EnableSendfile Off" >> /etc/apache2/apache2.conf
RUN echo "EnableMMAP Off" >> /etc/apache2/apache2.conf
RUN echo "FileETag None" >> /etc/apache2/apache2.conf
RUN echo "Header unset ETag" >> /etc/apache2/apache2.conf

WORKDIR /var/www/html
COPY public/assets/images/default.png /tmp/default.png
COPY docker/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]

EXPOSE 80